######################################################################
# Automatically generated by qmake (3.0) Thu Sep 21 06:09:45 2017
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets


TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += main.cpp
