######################################################################
# Automatically generated by qmake (3.0) Thu Sep 21 03:50:34 2017
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = slot_test
INCLUDEPATH += .

# Input
SOURCES += test.cpp
