######################################################################
# Automatically generated by qmake (3.0) Thu Sep 21 08:48:51 2017
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 18_event
INCLUDEPATH += .

# Input
SOURCES += main.cpp
