######################################################################
# Automatically generated by qmake (3.0) Thu Sep 21 03:57:45 2017
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = lambda
INCLUDEPATH += .

# Input
SOURCES += test.cpp
