######################################################################
# Automatically generated by qmake (3.0) Thu Sep 21 04:10:34 2017
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = observer_mode
INCLUDEPATH += .

# Input
HEADERS += newspaper.h reader.h
SOURCES += main.cpp
